### ISSUE TITLE
Lessen 6, practical example: Draw a rectangle at a precise position

### ISSUE THREAD

**Issue by golddotasksquestions** [GDQuest/learn-gdscript#67]
**Describe the bug**
Pressing "Run" without changing the existing code will stop execution of the app.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lessen 6, practical example: Draw a rectangle at a precise position
2. Click on Run without changing the script
3. This stops the app, opens Godot Editor if you run the app from the Godot Editor at TestDrawing Rectangles line 23
4. red Error says: "Invalid call. Nonexisting function 'sort' in base 'PoolVectorArray'."

Edit: Apparently the error also occurs when the correct solution is given and "Run" is pressed.

**Expected behavior**
app not stopping execution, instead an in-app error telling me I need to change the script.

**Screenshots**
![image](https://user-images.githubusercontent.com/47016402/147726831-ed53e62b-3157-43fb-b21d-467e1cd3e6ee.png)

**Information about your device (please complete the following information):**
 - Win64

**Additional context**
- running the app from the Godot editor

**Comment by Xananax** [comment]
This should be fixed by bffe814785d5e819a9ee9d0f7e2208c2201e8433

**Comment by NathanLovato** [comment]
Thanks for the bug report. Let's leave the issue open for now and test with the next deploy. It was the same segfault issue with duplicating the polygon points?

**Comment by allkhor** [comment]
> This should be fixed by [bffe814](https://github.com/GDQuest/learn-gdscript/commit/bffe814785d5e819a9ee9d0f7e2208c2201e8433)

Unreachable code after return?
https://github.com/GDQuest/learn-gdscript/blob/0554d064461ca8edb8ff857ad61edb2e51817e5f/game_demos/DrawingTurtle.gd#L238-L241
You missed:
https://github.com/GDQuest/learn-gdscript/blob/0554d064461ca8edb8ff857ad61edb2e51817e5f/course/lesson-7-member-variables/draw_rectangle_at_position/TestsDrawingRectangles.gd#L22-L23

https://github.com/GDQuest/learn-gdscript/blob/0554d064461ca8edb8ff857ad61edb2e51817e5f/course/lesson-7-member-variables/draw_rectangles_at_positions/TestsDrawingRectangles.gd#L16-L17
